# Google Cloud Platform config file
#
# TODO: Need to assign values to each of the env vars, (securely, not on GitHub,) before the app will run.
# NOTE: Make sure only single quotes are used, including for FIREBASE_SERVICE_PRIVATE_KEY.
#
# [START runtime]
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
#readiness_check:
#  path: "/health"
#  check_interval_sec: 5
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#  app_start_timeout_sec: 300
env_variables:
  NODE_ENV: 'production'
  FIREBASE_SERVICE_PROJECT_ID: ''
  FIREBASE_SERVICE_PRIVATE_KEY_ID: ''
  FIREBASE_SERVICE_PRIVATE_KEY: ''
  FIREBASE_SERVICE_CLIENT_EMAIL: ''
  FIREBASE_SERVICE_CLIENT_ID: ''
  FIREBASE_SERVICE_AUTH_URI: ''
  FIREBASE_SERVICE_TOKEN_URI: ''
  FIREBASE_SERVICE_AUTH_PROVIDER_X509_CERT_URL: ''
  FIREBASE_SERVICE_CLIENT_X509_CERT_URL: ''
  GOOGLE_CLOUD_STORAGE_BUCKET: ''
  AUTH_SECRET: ''
  AUTH_USERNAME: ''
  AUTH_PASSWORD: ''
  LEAGUE_TABLE_URL: ''
# [END runtime]
